# Generated by Django 4.2.19 on 2025-03-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_customer_options_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
