# Generated by Django 4.2.19 on 2025-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
